version: '3.1'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2-amd64
        restart: "no"
        container_name: elasticsearch
        command: ./elasticsearch -E "discovery.type=single-node"
        ports:
            - 9200:9200
        environment:
            - "ES_JAVA_OPTS=-Xms500M -Xmx500M"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.2-amd64
        restart: "no"
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            - elasticsearch_url=http://127.0.0.1:9200
        depends_on:
            - elasticsearch
    # fluentd:
    #     image: custom-fluentd
    #     container_name: fluentd
    #     # volumes:
    #     #     - ./fluentd/conf:/fluentd/etc
    #     links:
    #         - 'elasticsearch'
    #     ports:
    #         - '24224:24224'
    #         - '24224:24224/udp'