version: '3.1'
services:
  #服务名称
  mssql:
    #容器名称
    container_name: mssql
    #镜像名称
    image: mcr.microsoft.com/mssql/server:2019-latest
    #总是重启后启动
    restart: "no"
    #端口映射
    ports:
      - 1433:1433
    #挂载
    volumes:
      - ./data:/var/lib/rabbitmq
    #环境变量
    environment:
      - ACCEPT_EULA=Y
      #SA用户密码
      - SA_PASSWORD=MSSQL!123